### ISSUE TITLE
Add login screen

### ISSUE THREAD

**Issue by danielsilvayanez** [danielsilvayanez/capstone-project#10]
## Value statement - a requirement, not a solution
As a driver 
I want to be able to create and see memos that were made for each task 
so that my dispatcher and I can see a memo-history 

## Description (Text, Scribble, Wireframe, Design)
<img width="311" alt="Bildschirmfoto 2020-07-04 um 09 48 21" src="https://user-images.githubusercontent.com/65212631/86507872-c2afa580-bddb-11ea-8a80-6b43df4fa35a.png">

<img width="450" alt="Scribble3" src="https://user-images.githubusercontent.com/65212631/86447651-f4f6cf80-bd15-11ea-98a7-3aef2222064c.png">

## Acceptance criteria
- [ ] Memos can be entered
- [ ] Memos will be saved in area below
- [ ] Memo history should be expandble and hideable
- [ ] Memo is saved by just clicking enter?!
      
## Tasks
- [ ] Create feature branch (task-memos)
- [ ] Create component in Storybook
- [ ] Write component tests
- [ ] Add input field for memos
- [ ] Add button to add new memo
- [ ] Add memos-textarea 
- [ ] Save and get data from localStorage
- [ ] Write integration tests w/ Cypress

## Size
large
