### ISSUE TITLE
Task Form

### ISSUE THREAD

**Issue by danielsilvayanez** [danielsilvayanez/capstone-project#2]
## Value statement - a requirement, not a solution
As a dispatcher 
I need to create new tasks/jobs for our drivers
so that drivers know which customer they have to drive to

## Acceptance criteria
- [ ] Page-styling should orientate on https://ctsservice.de/
- [ ] After clicking on button "Neuer Auftrag", Form should appear (slide in)
- [ ] Form should contain the following fields :Call-No(text), Date(date), Driver(dropdown), notes (textarea) 
- [ ] After clicking on button "Neuer Auftrag", Form should appear
- [ ] after clicking on "erstellen" : 1. preventDefault, 2. reset entries 3. hide/close form
- [ ] Data-validation should be possible (min(x), max(x), required, string, number)
- [ ] ...
      
## Tasks
- [ ] (todos for the team)

## Size
(small, medium, large)
