### ISSUE TITLE
setup project

### ISSUE THREAD

**Issue by danielsilvayanez** [danielsilvayanez/capstone-project#6]
## Tasks
Installation
- [ ] styled-components
- [ ] storybook

Configuration
- [ ] create .prettierrc
- [ ] complete/add to .gitignore
- [ ] create folder "images" und "src"
- [ ] create folder "hooks" und "src"
- [ ] create folder "pages" und "src"

Deletion
- [ ] delete all .css files
- [ ] src -> logo.svg
- [ ] Public -> favicon.ico, logo.png, manifest.json?, robots.txt
